### ISSUE TITLE
const support

### ISSUE THREAD

**Issue by JMLX42** [Tomasu/LuaGlue#10]
Hello,

I closed my original "VS2013 support" issue (#1) because my pull request should fix it.
Here is an error I get with both VS2013 and GCC 4.8.1 regarding constness:

<pre>
error: value-initialization of reference type ‘const std::basic_string<char>&’
</pre>

- the LuaGlueMethod constructor init. list is trying to build an std::tuple that can store the arguments
- but one of my arguments is a const std::string& and as you might know, you can't create a container templated by const types (types have to be copy-constructible and assignable)

As you can imagine, not being able to store const types is a big problem. What are our options to make this work? Maybe make our std::tuple to be template not by the types themselves but by the equivalent pointer types (const std::string& would be stored as (const std::string&)*). What do you think?

Thanks again,

**Comment by JMLX42** [comment]
Ok so AFAIK this is the only remaining big issue that prevents my code from compiling.
How could we fix this? How can I help?

**Comment by Tomasu** [comment]
I'm a bit busy the next couple days, but I will take a look at this later this week. your suggestion to mangle the types to be pointers has promise I think. We'd just mangle it back to remove the extra pointer when actually doing the calling.

**Comment by JMLX42** [comment]
I'm exploring another solution: using a recursive meta function to call std::remove_const on Args...
I'll let you know.

**Comment by JMLX42** [comment]
I fixed it, I'll do a pull request soon.

**Comment by JMLX42** [comment]
Constness is now partially fixed thanks to the changes above.

Another constness issue is still not solved: (member) functions marked as const cannot be bound.

<pre>
class Foo
{
  public:
    void bar() const;
}
</pre>

<pre>
state.Class<Foo>("Foo").method("bar", &Foo::bar); // does not compile: cv-qualifier mismatch error
</pre>

I've tried to solve this without success...
Any idea?

**Comment by Tomasu** [comment]
Pushed up a fix for that. It was rather annoying, as it needed a bunch of code to be copy and pasted, with one small change to bits. but it works now.
