### ISSUE TITLE
change DEBUG into LG_DEBUG

### ISSUE THREAD

**Issue by JMLX42** [Tomasu/LuaGlue#19]
Hello,

I'm using LuaGlue to have a script system for our 3D engine. We use it to call Lua methods from C++. We do this at every frame with multiple methods (one per script) and the calls to LG_Debug are slowing everything down/make it hard or useless to print things in the console.

I would find it easier to use to have a specific LG_DEBUG or LUAGLUE_DEBUG macro.

What do you think?

**Comment by Tomasu** [comment]
Is there a specific reason you can't just not define DEBUG?

**Comment by JMLX42** [comment]
I'm using LuaGlue inside my 3D framework which also defines a DEBUG macro. So I can't turn LuaGlue's debug output without disabling the 3D framework debug output too.

**Comment by Tomasu** [comment]
Ok, I can rename the debug macro.

**Comment by JMLX42** [comment]
FYI I think I will also rename my debug macro into something more specific.
