### ISSUE TITLE
Can't compile LuaGlue

### ISSUE THREAD

**Issue by Gintasz** [Tomasu/LuaGlue#20]
Hi,
I'm trying to use LuaGlue in my simple android game engine using android ndk(basically c++). I'm getting some compilation errors, when compiling. I changed
# include < tuple>

to
# include < tr1\tuple> (no space actually)

and added std:: namespace when declaring variable with tuple type in LuaGlueMethod.h. This fixed half of errors, but some are still left: http://pastebin.com/i5VN4KdP

Do you have any idea how can I solve them?

EDIT: I removed these lines with "template... using tuple = std::tuple...", added "#include < stdexcept>" in LuaGlueObject.h and it compiles fine now.

**Comment by Tomasu** [comment]
LuaGlue absolutely requires proper C++11 support.  And that funky using code is required to work around some issues. If at all possible, try upgrading gcc to 4.8.

**Comment by gintasz** [comment]
Yes, you are absolutely right. Thanks.
