### ISSUE TITLE
passing C++ objects to LUA

### ISSUE THREAD

**Issue by JMLX42** [Tomasu/LuaGlue#3]
Hello,

when my C++ class is "mapped" using the Class<C>() and Method() syntax as in your example, how can I pass an object of class C to a LUA function called from my C++ code ?

Regards,

**Comment by Tomasu** [comment]
calling lua code from C++ wasn't implemented at all prior to just now. It's not complete, you can only invoke methods that are attached to class in some form. I haven't yet decided how I'll be supporting dynamic calling of global lua functions just yet. check the new invoke.cpp/invoke.lua example.

**Comment by JMLX42** [comment]
Outstanding! Looks like your work is getting more and more in the perfect direction every day :)
As I understand it your example and this changes make it quite straight forward to pass any object of class C that has been previously described using your Class/Method API.

Is that correct ?

If it is, then sir you're my hero :) Just have to solve the other issues and you'll have make it possible for us to add scripting to our 3D engine. Just so you know, we're building somekind of open source alternative to Unity, so the scripting system and its flexibility are a huge priority.

**Comment by Tomasu** [comment]
Yeah, you can actually pass any object into a method, it helps if its already registered with LuaGlue, but it isn't required. If it isn't registered, your lua will get it as a dumb opaque handle, which you can pass around back and forth between lua and C++, what you can't do with those handles is call methods or access properties on them.

The nice thing about this api is you don't have to wrap it yourself. Just pass it into the invoke(Void)Method as a parameter and LuaGlue takes care of the rest.

**Comment by JMLX42** [comment]
Looks like this is properly implemented. I'm ok to close this.
Thanks,
