### ISSUE TITLE
Unable to look up class by name later when passing a temporary string to LuaGlue::Class<>

### ISSUE THREAD

**Issue by jhanssen** [Tomasu/LuaGlue#42]
The problem is that LuaGlue::Class<>() takes a const std::string& and passes the c_str() on and the const char\* representation of the std::string gets stored in the symtab. However, if the std::string gets destroyed then the name in the symtab is now pointing to free'd memory and this makes it impossible (and unsafe) to call LuaGlue::lookupClass() with internal_name set to true.

**Comment by jhanssen** [comment]
Just wanted to mention that the same thing is true for LuaGlueClass<>::property() which means that the following won't work properly:

``` C++
glue.Class<foo>("foo").property("bar", &foo::bar)
```

``` lua
local f = foo.new()
local bar = f.bar
```

since a temporary std::string is created for property() and destroyed when it returns. However, a lookup by name is performed later when accessing the property from Lua but the name in the property symtab is no longer pointing to valid memory.

**Comment by Tomasu** [comment]
Thanks for the report. Especially since it was so clear and detailed. Much props to you!

**Comment by JMLX42** [comment]
I've actually solved this one. The problem occurred especially on Windows/VS.
I'll try to do a pull request ASAP.

**Comment by Tomasu** [comment]
I just pushed up a fix for it. Was a rather simple fix actually. Really just a derp on my part.

**Comment by jhanssen** [comment]
Thanks!
