### ISSUE TITLE
LuaGlue from dynamically loaded shared library segfaults

### ISSUE THREAD

**Issue by DirkWillem** [Tomasu/LuaGlue#43]
Hello.

I'm trying to bind a class from a shared library to lua with LuaGlue, but I get a segfault.
My code:

main.cpp:

``` C++
#include <iostream>
#include <dlfcn.h>

#include <LuaGlue/LuaGlue.h>
#include <lualibrary/LuaLibrary.hpp>


void loadLibrary(const char* file, LuaGlue* state){
    using std::cerr;

    void* library = dlopen("./foolib.so", RTLD_NOW);
    if (!library) {
        std::cerr << "Cannot load library: " << dlerror() << '\n';
        return;
    }

    typedef LuaLibrary* create_t();
    typedef void destroy_t(LuaLibrary*);

    create_t* createLibrary = (create_t*) dlsym(library, "create");
    destroy_t* destroyLibrary = (destroy_t*) dlsym(library, "destroy");
    if (!createLibrary || !destroyLibrary) {
        cerr << "Cannot load symbols: " << dlerror() << '\n';
        return;
    }

    LuaLibrary* lib = createLibrary();
    lib->load(state);
    destroyLibrary(lib);

    dlclose(library);
}

int main(int argc, const char** argv){
    LuaGlue* state = new LuaGlue();

    loadLibrary("./foolib.so",state);
    state->open().glue();

    state->doFile("test.lua");
}
```

foolib.cpp

``` C++
#include <LuaGlue/LuaGlue.h>
#include <lualibrary/LuaLibrary.hpp>

#include <cstdio>

class Foo{
    public:
        Foo(int n){printf("%i",n);}
        void method(){printf("Method");}
};

class FooLibrary : public LuaLibrary{
    public:
        void load(LuaGlue* state){
            state->
                Class<Foo>("Foo").
                    ctor<int>("new").
                    method("method",&Foo::method).
                end();
        }
};

extern "C" LuaLibrary* create(){
    return new FooLibrary();
}

extern "C" void destroy(LuaLibrary* lib){
    delete lib;
}
```

LuaLibrary.hpp:

``` C++
#ifndef LUALIBRARY_HPP
#define LUALIBRARY_HPP

#include <LuaGlue/LuaGlue.h>

class LuaLibrary{
    public:
        virtual void load(LuaGlue* state){}
};

#endif
```

test.lua:

``` Lua
local foo = Foo.new(5)
foo:method()
```

When I compile this, I get a segmentation fault. I found out that the classes from the shared library aren't actually bound to the state, because I get similar results by not binding any classes.

My system is a Ubuntu virtual box, using Clang++

**Comment by Tomasu** [comment]
That could be due to memory management barriers between the library and your program. Try passing in your own lua_State handle to open(). If that doesn't work, it may require some changes to how memory is managed in LuaGlue.

**Comment by DirkWillem** [comment]
No, passing my own state doesn't change a thing. Thats logical, because the LuaGlue instance is instantiated in `main.cpp`, and only a pointer to it is passed to the shared library

**Comment by Tomasu** [comment]
Hm, what if you create the LuaGlue in the shared object? I might need some way to pass in an allocator...

**Comment by DirkWillem** [comment]
OK, that doesn't work. Also, it's not really an option for me. I need to be able to load more dynamic libraries at runtime (otherwise I would have implemented the object in my application).

But anyway, the code; (it still segfaults)

`main.cpp`:

``` C++
#include <iostream>
#include <dlfcn.h>

#include <LuaGlue/LuaGlue.h>
#include <lualibrary/LuaLibrary.hpp>


LuaGlue* loadLibrary(const char* file){
    using std::cerr;

    void* library = dlopen("./foolib.so", RTLD_NOW);
    if (!library) {
        std::cerr << "Cannot load library: " << dlerror() << '\n';
        return nullptr;
    }

    typedef LuaLibrary* create_t();
    typedef void destroy_t(LuaLibrary*);

    create_t* createLibrary = (create_t*) dlsym(library, "create");
    destroy_t* destroyLibrary = (destroy_t*) dlsym(library, "destroy");
    if (!createLibrary || !destroyLibrary) {
        cerr << "Cannot load symbols: " << dlerror() << '\n';
        return nullptr;
    }

    LuaLibrary* lib = createLibrary();
    LuaGlue* state = lib->getGlue();
    destroyLibrary(lib);

    dlclose(library);

    return state;
}

int main(int argc, const char** argv){

    LuaGlue* state = loadLibrary("./foolib.so");
    state->open().glue();

    state->doFile("test.lua");
}
```

`LuaLibrary.hpp`:

``` C++
#ifndef LUALIBRARY_HPP
#define LUALIBRARY_HPP
#include <LuaGlue/LuaGlue.h>

class LuaLibrary{
    public:
        virtual LuaGlue* getGlue(){return nullptr;}
};

#endif
```

`foolib.cpp`

``` C++
#include <LuaGlue/LuaGlue.h>
#include <lualibrary/LuaLibrary.hpp>

#include <cstdio>

class Foo{
    public:
        Foo(int n){printf("%i",n);}
        void method(){printf("Method");}
};

class FooLibrary : public LuaLibrary{
    public:
        LuaGlue* getGlue(){
            LuaGlue* state = new LuaGlue();
            state->
                Class<Foo>("Foo").
                    ctor<int>("new").
                    method("method",&Foo::method).
                end();
            return state;
        }
};

extern "C" LuaLibrary* create(){
    return new FooLibrary();
}

extern "C" void destroy(LuaLibrary* lib){
    delete lib;
}
```

Maybe also interesting (although I don't think so...)
`build.sh`:

``` Sh
#!/bin/sh

echo "Building Library..."
clang++ -I/usr/include/lua5.2 \
    -I/home/dirk/Documents/lualibtest/libraries \
    -llua5.2 foolib.cpp -fPIC -shared -std=c++11 -o foolib.so
echo "Building main.cpp..."
clang++ -I/usr/include/lua5.2 \
    -I/home/dirk/Documents/lualibtest/libraries \
    -llua5.2 -ldl main.cpp -std=c++11 -o main
echo "Done"
```

**Comment by DirkWillem** [comment]
Also tested moving the open and glue to the library, but then it still doesn't work as Lua doesn't seem to find the `Foo` class

**Comment by Tomasu** [comment]
I'll take a look into it soon. I'm not entirely sure what is going on. Lua might not like being shared across boundaries. can you post a backtrace?

**Comment by DirkWillem** [comment]
OK, I'll look into that tomorrow (I live in Europe)

**Comment by DirkWillem** [comment]
OK, did another test where I removed all LuaGlue code from `main.cpp` and moved it all to the shared library. Everything goes alright untill I call the "glue" method. (the Lua state is passed to the library as an argument)

**Comment by DirkWillem** [comment]
OK, tried a lot of stuff, and I found out that the `glue` method does something to the lua_State, that whenever I try to use it afterwards with regular Lua commands (like `lua_close`), it segfaults

**Comment by DirkWillem** [comment]
And using LuaGlue in a shared object loaded with Lua's shared object loader from Lua also segfaults, so it must have to do something with what LuaGlue does to the lua_State

**Comment by Tomasu** [comment]
Looking closer at your code, it seems you destroy your plugin object and close the shared lib before you try and run it. I just added a test that seems to work fine. try it out, see if it works for you.

**Comment by DirkWillem** [comment]
Yes, that works! thank you!

**Comment by Tomasu** [comment]
I may add LuaPluginBase as a standard part of the api, and a LuaGluePluginFactory or something to work cross platform. Depends on interest.
