### ISSUE TITLE
Duplicate Symbols on XCode.

### ISSUE THREAD

**Issue by PhilCK** [Tomasu/LuaGlue#45]
I have an issue where XCode spews out loads of 'duplicate symbols' for 'LuaGlue::getGlobal's.

I'm unsure why, as my early LuaGlue tests where done with clang++ and a makefile without issue.

I don't know if its a legitimate (I say that as I'm still have a few issues.) but I inlined all the getGlobal methods and it seems to have solved those issues.

XCode
Lua as C++ (not as library)

**Comment by PhilCK** [comment]
Just to say my other issues, where when I wrapped a state in another object then used then made a copy of that object, so I doubt that has todo with the duplicate symbols.

**Comment by Tomasu** [comment]
Hm, are you saying that Using more than one LuaGlue object causes duplicate symbols? Or is that not related to the non inlined getGlobals?

**Comment by Tomasu** [comment]
I've committed a fix for the inline issue.
