### ISSUE TITLE
Visual Studio 2013.

### ISSUE THREAD

**Issue by PhilCK** [Tomasu/LuaGlue#46]
I've had a few issues getting LuaGlue working with MSVS 2013. I had some issues that have been reported with LuaGlueDebug.h around the macros LG_Debug(a, b...). I changed them to LG_Debug(a, ...), unsure if that was the correct thing todo or not.

Now I have an issue where I get an infinitely unhelpful message "Optimizing Compiler has stopped working." After some searching it seems an there are many reasons for this to happen.

It crashes on LuaGlueMethod.h line 116 "tuple<_Args ...> args;"

I don't know if anybody has any success with Visual Studio or not, I'll keep trying to get to the bottom of it.

**Comment by Tomasu** [comment]
I've replaced the use of the older style gcc macro varargs with std **VA_ARGS**. That should fix the first error. As for the other errors... I don't know. Can you try to make sure your compiler is up to date? Last I heard MSVS's C++11 compiler wasn't quite complete. I know some people have been able to use it...

**Comment by Tomasu** [comment]
I may have fixed the issues regarding `tuple<_Args...> args`. I've replaced the using statement with a typedef. Please let me know if this helps.

**Comment by Tomasu** [comment]
Closing for now. If you still have this problem, reopen.
