### ISSUE TITLE
Error while compiling (MinGW)

### ISSUE THREAD

**Issue by DominikMS** [Tomasu/LuaGlue#53]
LuaGlueMethod.hp[24]

```
using tuple = std::tuple<typename std::remove_const<typename std::remove_reference<T>::type>::type...>;
```

wrong number of template arguments (0, should be 1)
wrong number of template arguments (3, should be 1)

Remove line and change:
tuple<_Args...> args;
to:
std::tuple<_Args...> args;

---

And this one after run:

```
terminate called after throwing an instance of 'std::runtime_error'
what():  random_device::random_device(const std::string&)
```

I change to rand()

**Comment by Tomasu** [comment]
the first issue is actually on purpose, and fixes an issue with msvc I think.

The second, I'm not sure what's up. It's a stock C++11 class, if it doesn't work, your compiler or os may be broken. I have not seen that issue.

Can you tell me what OS and compiler you're using.

**Comment by DominikMS** [comment]
MinGW GNU 4.8.1
Windows 8

**Comment by Tomasu** [comment]
That is weird, I did not have that problem yesterday when I fixed some build errors in the examples in msys2 (mingw 4.8.1).

Makes me think you're not using it properly? can you post a simplified example that has the template issue?

**Comment by DominikMS** [comment]
http://speedy.sh/p8use/Android-engine.rar

There is my full code (without exe).

---

@edit
not wasting new issue...
Pushing pointers is safe for memory leak?

**Comment by Tomasu** [comment]
Would you be able to post a simplified example that shows your problem?

**Comment by Tomasu** [comment]
What do you mean by pushing pointers? "pushInstance" ? that should be fine.

**Comment by DominikMS** [comment]
Yes, pushInstance.

---

```
class ClassA {

    public:
        ClassA(std::string str) { }
        ~ClassA() { }

        bool test()  { return true; }
};
```

```
    state.
        Class<ClassA>("ClassA").
        method("test", &ClassA::test).
    end();
```

Full error log:

```
  required from 'LuaGlueClass<_Class>& LuaGlueClass<_Class>::method(const string&, _Ret (_Class::*)(_Args ...)) [with _Ret = bool; _Args = {}; _Class = ClassA; std::string = std::basic_string<char>]' LuaGlueClass.h  /Android_engine/libs/LuaGlue    line 374    C/C++ Problem
provided for 'template<class> struct std::remove_reference' Android_engine      line 790, external location: c:\mingw\lib\gcc\mingw32\4.7.2\include\c++\type_traits C/C++ Problem
make: *** [Android_engine.o] Error 1    Android_engine          C/C++ Problem
  required from here    Android_engine.cpp  /Android_engine line 73 C/C++ Problem
wrong number of template arguments (0, should be 1) LuaGlueMethod.h /Android_engine/libs/LuaGlue    line 24 C/C++ Problem

```

@edit

```
// tuple<_Args...> args; // old
std::tuple<typename std::remove_const<typename std::remove_reference<_Args>::type>::type...> args;
```

This one is working well for me.

**Comment by Tomasu** [comment]
All I can say right now is this works fine in mingw/msys2, and linux for me. All of the examples compile fine.

I don't see what is different with your code than what the examples do, but I'll try it later anyhow.

**Comment by Tomasu** [comment]
Ok, I can see a possible issue with the current tuple<_Args...> version. I'll have to mess with that.

**Comment by DominikMS** [comment]
And something else.
Please remove all #include <lua.hpp> except LuaGlue.hpp

**Comment by Tomasu** [comment]
I don't understand what you mean? I can't remove includes for things like string, and type traits, etc.

**Comment by DominikMS** [comment]
Damn! This writer remove file " < lua.hpp > "
So i mean: all #include < lua.hpp >

**Comment by Tomasu** [comment]
I'd prefer not to. LuaGlue itself depends heavily on lua. why do you want me to remove it?

**Comment by Tomasu** [comment]
Ok, this might be fixed, but I have no idea, as I don' thave the problem.

**Comment by DominikMS** [comment]
[runtime_error random_device] problem still exist, but this is compiler bug, thread to close.

**Comment by Tomasu** [comment]
Ok. I'll look at the runtime_error next.
