### ISSUE TITLE
Overloaded functions?

### ISSUE THREAD

**Issue by ricanteja** [Tomasu/LuaGlue#62]
Is there a way to bind overloaded class functions with LuaGlue?
I tried but couldn't figure it out.
(I just tried method<float>("my_func", &MyClass::MyFunc).)

Sorry to post this here, is there any other way to get in touch with you?
I'd hate to pollute your Git with user questions..

**Comment by DominikMS** [comment]
I think this is not possible.

**Comment by ricanteja** [comment]
Ok I thought so, I checked the examples and found nothing about it.
Whenever I have a question about how to implement something with LuaGlue I just scan through the source code of the example projects but it's hardly a good place for people to learn from.

**Comment by DominikMS** [comment]
Everythings are in examples. This is not hard to learn if you know c++.

**Comment by ricanteja** [comment]
I'd argue that having documentation makes learning faster than reading source code.

**Comment by Tomasu** [comment]
I think it is possible if you specifically cast the method pointer to the right signature first. I think.

You are right that documentation is needed. but I don't have a lot of time for personal projects, and theres a lot of work to be done on the code itself still. :(

**Comment by ricanteja** [comment]
I completely understand and trust me I appreciate everything you are doing with this project. Maybe I could write documentation for you?

**Comment by Tomasu** [comment]
Contributions are always welcome :) :+1:

**Comment by ricanteja** [comment]
Alright then, I'll work on it after I get somewhere noticeable with my project.
