### ISSUE TITLE
Cannot compile under VS 2013

### ISSUE THREAD

**Issue by amerkoleci** [Tomasu/LuaGlue#63]
I cannot compile usage of LuaGlue as it includes cxxabi.h which is not avaiable on Visual Studio and windows platforms.

**Comment by DominikMS** [comment]
Do you need gcc 4.7.2 or higher.

**Comment by Tomasu** [comment]
Sorry about that. The macros that use it really should get a msvc implementation. I'm currently non vacation, so I don't have time to fix it... But I'll try and get it done when I get back.

**Comment by Tomasu** [comment]
Please let me know if this is fixed. Thanks.
