### ISSUE TITLE
Properties support

### ISSUE THREAD

**Issue by JMLX42** [Tomasu/LuaGlue#7]
Hello,

I would like to use Lua's metatables to implement the concept of properties through getter/setter functions.

Here is what I do in C++:

<pre>
class Foo
{
  private:
    int _bar;

  public:
    int bar() { return _bar; }

    void bar(int bar) { _bar = bar; }
};
</pre>

Here is how I'd like to use it in lua:

<pre>
// assuming f is a Foo instance mapped through LuaGlue
f.bar = 42 // call void Foo::bar(int)
print(f.bar) // call int Foo::bar()
</pre>

I know other Lua binding system make it possible by declaring the proper metatable. How can I add a Property method (similar to your Class and Method functions) that would do this?

Thanks again for the great work!

**Comment by Tomasu** [comment]
Hm, actually, I've already implemented properties, except they don't go through setters and getters. the code will set and get any public properties you register. I know that's a bit dirty..

I think I can extend the LuaGlueClass "index" methods to dispatch to setters and getters. I'll look into that as well.

**Comment by JMLX42** [comment]
Cool. Public properties are a no go for us of course so this is a major improvement. Declaring "setX" and "getX" Lua method could work but it would mean our Lua interface would be different from the C++ one and that's not good.

Thanks again!

**Comment by Tomasu** [comment]
I think what needs to be done there is a new property() method that takes the property name, and two method pointers, then a new LuaGlueProperty like class to dispatch to those methods, rather than the direct access that the current one does. it should be mostly transparent.

**Comment by Tomasu** [comment]
Done.
