### ISSUE TITLE
non-static members

### ISSUE THREAD

**Issue by JMLX42** [Tomasu/LuaGlue#72]
Hi,

we're using a probably outdated version of LuaGlue in Minko (http://github.com/aerys/minko) and we're in the process of updating it. Still, while we're working on this, I'd like to know if the current (major) issue we're facing has been solved.

It would seam the way LuaGlue defines the metatables - and especially the way things like the _index metamethod is implemented - make it impossible to have non-static members. Indeed, it's like every member is written directly in the metatable itself instead of the table. As each table of a given "class" share the same metatable, all member de facto become somekind of static member.

Did anyone report this and has it been fixed?

Regards,

**Comment by Tomasu** [comment]
Do you mean to say that all instances of a given class will share all of the same data? I am not seeing that kind of behavior in the current master branch.

**Comment by JMLX42** [comment]
OK I'll give it a try and report. It should be easy to test...

**Comment by JMLX42** [comment]
Ok I just tested the "props" example doing this:

```
foo2 = Foo.new()

print("get direct props:")

print("foo.int: "..foo.d_int)
print("foo.char: "..foo.d_char)
print("foo.sstr: "..foo.d_sstr)
print("foo.objptr: "..foo.d_objptr)
print("foo.objsptr: "..foo.d_objsptr)
print("foo.obj: "..foo.d_obj)

print("get direct props:")

print("foo2.int: "..foo2.d_int)
print("foo2.char: "..foo2.d_char)
print("foo2.sstr: "..foo2.d_sstr)
print("foo2.objptr: "..foo2.d_objptr)
print("foo2.objsptr: "..foo2.d_objsptr)
print("foo2.obj: "..foo2.d_obj)
```

I do get different values for foo2 and foo properties so it seams all is fine now :)

**Comment by Tomasu** [comment]
Yeah, it is possible that the old glue() method in LuaGlueClass did a couple of things in the wrong order. A bunch of stuff got refactored and fixed in the past month or so.
