### ISSUE TITLE
Constant console output

### ISSUE THREAD

**Issue by ricanteja** [Tomasu/LuaGlue#76]
In the latest commit of LuaGlue I have this issue where a console window opens up and starts printing messages about function calls like this for example:

luaglue.h:invokeVoidFunction:138: STACK: 1:function,
luaglue.h:invokeVoidFunction:138: STACK: 1:function,
luaglue.h:invokeVoidFunction:138: STACK: 1:function,
luaglue.h:invokeVoidFunction:138: STACK: 1:function,
...
and it goes on like that for ever. How do I turn off these debug messages? LG_DEBUG seems to do nothing..

**Comment by Tomasu** [comment]
Sorry about that. LG_DEBUG should catch that.. I'll fix it, but in the mean time  go to luaglue.h line 138 and comment out the LG_Debug call there.

**Comment by ricanteja** [comment]
I had to comment a little bit more than that but you set me in the right direction! Thanks!
I'm looking forward to the big update btw ;)

**Comment by Tomasu** [comment]
Heh, I'll try and work on the update as I get time, but some other things have taken priority at the moment.
